project:
  type: website
  output-dir: docs

website:
  title: "Jody Holland Thesis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: modelling.qmd
        text: Statistical Modelling
      - href: control_variables.qmd
        text: Control Variables
      - text: Monthly LST
        menu:
          - href: lsjanuary.qmd
            text: January
          - href: lsmarch.qmd
            text: March 
          - href: lsmay.qmd
            text: May             
          - href: lsjuly.qmd
            text: July
          - href: lsseptember.qmd
            text: September 
          - href: lsnovember.qmd
            text: November
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

